server:
  applicationConnectors:
    - type: http
      port: 8181
  adminConnectors:
    - type: http
      port: 8182
mongo:
  uri: mongodb://localhost:27017/?maxPoolSize=50&maxIdleTimeMS=300000
  dbName: fileRepository